{% set python_min = '3.10' %}
{% set name = "pyheatdemand" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyHeatDemand-{{ version }}.tar.gz
  sha256: 1b1719952143cefba2fa8d4619b9cfc5846446d25ea0f1acc044cbfa6629ef8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68.1.2
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - geopandas
    - rasterstats
    - matplotlib-base
    - tqdm
    - geopy
    - osmnx

test:
  imports:
    - pyheatdemand
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: "https://github.com/AlexanderJuestel/pyheatdemand"
  summary: Processing Tool for Heat Demand Data
  license: LGPL-3.0-only
  license_file: LICENSE
  dev_url: "https://github.com/AlexanderJuestel/pyheatdemand"
  doc_url: "https://pyhd.readthedocs.io/en/latest/"

extra:
  recipe-maintainers:
    - AlexanderJuestel
